=== mihaelsegulja/java2-projekt/xml/game-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT game-config (rules, computer, ui)>

<!ELEMENT rules (
        starting-cards,
        must-call-uno,
        uno-penalty-cards,
        allow-stacking,
        draw-until-playable,
        initial-direction
        )>

<!ELEMENT computer (
        thinking-delay-min,
        thinking-delay-max,
        call-uno-probability
        )>

<!ELEMENT ui (
        enable-animations,
        show-playable-hints
        )>

<!ELEMENT starting-cards (#PCDATA)>
<!ELEMENT must-call-uno (#PCDATA)>
<!ELEMENT uno-penalty-cards (#PCDATA)>
<!ELEMENT allow-stacking (#PCDATA)>
<!ELEMENT draw-until-playable (#PCDATA)>
<!ELEMENT initial-direction (#PCDATA)>

<!ELEMENT thinking-delay-min (#PCDATA)>
<!ELEMENT thinking-delay-max (#PCDATA)>
<!ELEMENT call-uno-probability (#PCDATA)>

<!ELEMENT enable-animations (#PCDATA)>
<!ELEMENT show-playable-hints (#PCDATA)>

=== mihaelsegulja/java2-projekt/xml/game-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE game-config SYSTEM "game-config.dtd">
<game-config>

    <rules>
        <starting-cards>7</starting-cards>
        <must-call-uno>true</must-call-uno>
        <uno-penalty-cards>2</uno-penalty-cards>
        <allow-stacking>false</allow-stacking>
        <draw-until-playable>false</draw-until-playable>
        <initial-direction>CLOCKWISE</initial-direction>
    </rules>

    <computer>
        <thinking-delay-min>500</thinking-delay-min>
        <thinking-delay-max>1700</thinking-delay-max>
        <call-uno-probability>0.9</call-uno-probability>
    </computer>

    <ui>
        <enable-animations>true</enable-animations>
        <show-playable-hints>false</show-playable-hints>
    </ui>

</game-config>
